# Generated by Django 3.1.13 on 2021-09-30 09:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factual', '0003_add_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='relatives',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PARENTS_PRESENT', 'parents present'), ('PARENTS_ABSENT', 'parents absent'), ('SIBLINGS_PRESENT', 'siblings present'), ('SIBLINGS_ABSENT', 'siblings absent'), ('NONE', 'none'), ('UNKNOWN', 'unknown')], max_length=200), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='hero',
            name='role',
            field=models.CharField(choices=[('MAJOR', 'major character'), ('MINOR', 'minor character')], max_length=11),
        ),
    ]
