# Generated by Django 3.1.13 on 2021-09-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factual', '0004_auto_20210930_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='profession',
            field=models.TextField(choices=[('ARCHITECTURE', 'Architecture and engineering'), ('ARTS', 'Arts, culture, and entertainment'), ('BUSINESS', 'Business, management, and administration'), ('COMMUNICATIONS', 'Communications'), ('COMMUNITY', 'Community and social services'), ('EDUCATION', 'Education'), ('FARMING', 'Farming, fishing, and forestry'), ('GOVERNMENT', 'Government'), ('HEALTH', 'Health and medicine'), ('INSTALLATION', 'Installation, repair, and maintenance'), ('LAW', 'Law and public policy'), ('SALES', 'Sales'), ('SCIENCE', 'Science and technology'), ('OTHER', 'Other'), ('NONE', 'None'), ('UNKNOWN', 'Unknown')], default='unknown', max_length=200),
        ),
    ]
