# Generated by Django 3.1.13 on 2021-11-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factual', '0005_auto_20210930_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='education',
            field=models.TextField(choices=[('HIGH', 'high'), ('LOW', 'low'), ('OTHER', 'other'), ('NONE', 'none'), ('UNKNOWN', 'unknown')], default='unknown', max_length=7),
        ),
    ]
