# Generated by Django 3.1.13 on 2024-11-07 10:12

from django.db import migrations

from factual.models import RATING_QUESTIONS
from functools import partial

likert_5_7_mapping = {
    1: 1,
    2: 2,
    3: 2,
    4: 3,
    5: 4,
    6: 4,
    7: 5
}

likert_7_5_mapping = {
    1: 1,
    2: 3,
    3: 4,
    4: 5,
    5: 7,
}


class Migration(migrations.Migration):

    def likert_conversion(apps, schema_editor, mapping):
        Response = apps.get_model('factual', 'Response')
        for response in Response.objects.all():
            json_response = {
                key: mapping[value]
                if key in RATING_QUESTIONS
                else value
                for key, value in response.responses.items()
            }

            response.responses = json_response
            response.save()

    dependencies = [
        ('factual', '0006_auto_20211101_1336'),
    ]

    operations = [
        migrations.RunPython(
            partial(likert_conversion, mapping=likert_5_7_mapping),
            partial(likert_conversion, mapping=likert_7_5_mapping))
    ]
